name: app
description: eHealom App
publish_to: 'none'

version: 1.0.1+11

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.5
  image_picker: ^0.8.7
  http: ^0.13.5
  flutter_secure_storage: ^7.0.1
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.15
  path_provider: ^2.0.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - .env.dev
    - .env.prod
    - assets/images/logo.png
